# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Alert.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x41lert.proto\x12\x0frajant.bc.proto\x1a\x0c\x43ommon.proto\"6\n\x08\x41lertSet\x12*\n\x05\x65ntry\x18\x01 \x03(\x0b\x32\x1b.rajant.bc.proto.AlertEntry\"\xd1\x01\n\nAlertEntry\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12(\n\x04meta\x18\x02 \x01(\x0b\x32\x1a.rajant.bc.proto.AlertMeta\x12\x36\n\x08override\x18\x03 \x03(\x0b\x32$.rajant.bc.proto.AlertEntry.Override\x12\x0f\n\x07\x65numTxt\x18\x04 \x01(\t\x1a\x42\n\x08Override\x12\x0c\n\x04mode\x18\x01 \x01(\t\x12(\n\x04meta\x18\x02 \x01(\x0b\x32\x1a.rajant.bc.proto.AlertMeta\"\x90\x01\n\tAlertMeta\x12+\n\x04type\x18\x01 \x01(\x0e\x32\x10.Alert.AlertType:\x0bINFORMATION\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\x12\x61pplicationMessage\x18\x03 \x01(\t\x12\x11\n\x03led\x18\x04 \x01(\x08:\x04true\x12\x16\n\x07\x66\x61\x63tory\x18\x05 \x01(\x08:\x05\x66\x61lseB/\n\x11\x63om.rajant.alertsB\x0f\x41lertMetaProtosH\x02Z\x07\x62\x63proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Alert_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\021com.rajant.alertsB\017AlertMetaProtosH\002Z\007bcproto'
  _globals['_ALERTSET']._serialized_start=46
  _globals['_ALERTSET']._serialized_end=100
  _globals['_ALERTENTRY']._serialized_start=103
  _globals['_ALERTENTRY']._serialized_end=312
  _globals['_ALERTENTRY_OVERRIDE']._serialized_start=246
  _globals['_ALERTENTRY_OVERRIDE']._serialized_end=312
  _globals['_ALERTMETA']._serialized_start=315
  _globals['_ALERTMETA']._serialized_end=459
# @@protoc_insertion_point(module_scope)
