# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConfigMeta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x43onfigMeta.proto\x12\x0frajant.bc.proto\"Y\n\nConfigMeta\x12\x0c\n\x04path\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0c\n\x04help\x18\x03 \x01(\t\x12\x0f\n\x07\x63omment\x18\x04 \x01(\t\x12\x10\n\x08\x65numText\x18\x05 \x03(\t\"A\n\rConfigMetaSet\x12\x30\n\x0b\x63onfigMetas\x18\x01 \x03(\x0b\x32\x1b.rajant.bc.proto.ConfigMetaB6\n\x17\x63om.rajant.bcapi.protosB\x10\x43onfigMetaProtosH\x02Z\x07\x62\x63proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ConfigMeta_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.rajant.bcapi.protosB\020ConfigMetaProtosH\002Z\007bcproto'
  _globals['_CONFIGMETA']._serialized_start=37
  _globals['_CONFIGMETA']._serialized_end=126
  _globals['_CONFIGMETASET']._serialized_start=128
  _globals['_CONFIGMETASET']._serialized_end=193
# @@protoc_insertion_point(module_scope)
