# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FileTransfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x46ileTransfer.proto\x12\x0frajant.bc.proto\"\xd2\x01\n\x0c\x46ileTransfer\x12\x32\n\x05start\x18\x01 \x01(\x0b\x32#.rajant.bc.proto.FileTransfer.Start\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x0e\n\x06\x63\x61ncel\x18\x03 \x01(\x08\x12\x10\n\x08\x63lientId\x18\x04 \x01(\t\x12\x0c\n\x04\x64one\x18\x05 \x01(\x08\x1aP\n\x05Start\x12\x0e\n\x06\x61ppend\x18\x01 \x01(\x08\x12\x14\n\x0c\x65xpectedSize\x18\x02 \x02(\r\x12\x0f\n\x07version\x18\x03 \x02(\t\x12\x10\n\x08\x66ilename\x18\x04 \x01(\tB8\n\x17\x63om.rajant.bcapi.protosB\x12\x46ileTransferProtosH\x02Z\x07\x62\x63proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FileTransfer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.rajant.bcapi.protosB\022FileTransferProtosH\002Z\007bcproto'
  _globals['_FILETRANSFER']._serialized_start=40
  _globals['_FILETRANSFER']._serialized_end=250
  _globals['_FILETRANSFER_START']._serialized_start=170
  _globals['_FILETRANSFER_START']._serialized_end=250
# @@protoc_insertion_point(module_scope)
