# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Gps.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tGps.proto\"\xde\x04\n\x03GPS\x12(\n\tgpsSwitch\x18\x01 \x01(\x0b\x32\x15.GPS.GPSEnabledSwitch\x12&\n\x06gpsPos\x18\x02 \x01(\x0b\x32\x16.GPS.GPSPositionReport\x12&\n\x06gpsVel\x18\x03 \x01(\x0b\x32\x16.GPS.GPSVelocityReport\x12*\n\x06gpsRMC\x18\x04 \x01(\x0b\x32\x1a.GPS.GPSRecommendedMinimum\x1a#\n\x10GPSEnabledSwitch\x12\x0f\n\x07\x65nabled\x18\x01 \x01(\x08\x1a\xae\x01\n\x11GPSPositionReport\x12\x0f\n\x07gpsTime\x18\x01 \x01(\x02\x12\x0e\n\x06gpsLat\x18\x02 \x01(\t\x12\x0f\n\x07gpsLong\x18\x03 \x01(\t\x12\x15\n\rgpsPrecisionH\x18\x04 \x01(\x02\x12\x12\n\ngpsQuality\x18\x05 \x01(\x02\x12\x15\n\rgpsSatsInView\x18\x06 \x01(\r\x12\x0e\n\x06gpsAlt\x18\x07 \x01(\x02\x12\x15\n\rgpsGeoidalSep\x18\x08 \x01(\x02\x1ax\n\x11GPSVelocityReport\x12\x1b\n\x13gpsTrackDegreesTrue\x18\x01 \x01(\x02\x12\x1a\n\x12gpsTrackDegreesMag\x18\x02 \x01(\x02\x12\x15\n\rgpsSpeedKnots\x18\x03 \x01(\x02\x12\x13\n\x0bgpsSpeedKph\x18\x04 \x01(\x02\x1a\x61\n\x15GPSRecommendedMinimum\x12\x0f\n\x07gpsTime\x18\x01 \x01(\x02\x12\x11\n\tgpsStatus\x18\x02 \x01(\x08\x12\x0f\n\x07gpsDate\x18\x03 \x01(\x02\x12\x13\n\x0bgpsDateTime\x18\x04 \x01(\tB/\n\x17\x63om.rajant.bcapi.protosB\tGpsProtosH\x02Z\x07\x62\x63proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Gps_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.rajant.bcapi.protosB\tGpsProtosH\002Z\007bcproto'
  _globals['_GPS']._serialized_start=14
  _globals['_GPS']._serialized_end=620
  _globals['_GPS_GPSENABLEDSWITCH']._serialized_start=187
  _globals['_GPS_GPSENABLEDSWITCH']._serialized_end=222
  _globals['_GPS_GPSPOSITIONREPORT']._serialized_start=225
  _globals['_GPS_GPSPOSITIONREPORT']._serialized_end=399
  _globals['_GPS_GPSVELOCITYREPORT']._serialized_start=401
  _globals['_GPS_GPSVELOCITYREPORT']._serialized_end=521
  _globals['_GPS_GPSRECOMMENDEDMINIMUM']._serialized_start=523
  _globals['_GPS_GPSRECOMMENDEDMINIMUM']._serialized_end=620
# @@protoc_insertion_point(module_scope)
