# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Hardware.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eHardware.proto\x1a\x0c\x43ommon.proto\"\x8c\x05\n\x08Hardware\x12\x0e\n\x06serial\x18\x01 \x01(\t\x12\x0f\n\x07profile\x18\x02 \x01(\t\x12\r\n\x05imkey\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\x12\x12\n\nv10factory\x18\x05 \x01(\x0c\x12\x13\n\x0b\x63ountrycode\x18\x06 \x01(\r\x12,\n\x0corganization\x18\x07 \x01(\x0b\x32\x16.Hardware.Organization\x12\x1c\n\rimbcompatible\x18\x08 \x01(\x08:\x05\x66\x61lse\x12\x17\n\x0f\x61llowDfsControl\x18\n \x01(\x08\x12,\n\x0clinkedDevice\x18\x0b \x03(\x0b\x32\x16.Hardware.LinkedDevice\x12&\n\tboardData\x18\r \x01(\x0b\x32\x13.Hardware.BoardData\x12(\n\ndeployment\x18\x0e \x01(\x0b\x32\x14.Hardware.Deployment\x1a@\n\x0cOrganization\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x64ivision\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x1a;\n\x0cLinkedDevice\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1f\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\n.BCRAction:\x03\x41\x44\x44\x1a;\n\x0b\x41ssignedMac\x12\x0b\n\x03mac\x18\x01 \x01(\x0c\x12\x1f\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\n.BCRAction:\x03\x41\x44\x44\x1aV\n\tBoardData\x12*\n\x0b\x61ssignedMac\x18\x01 \x03(\x0b\x32\x15.Hardware.AssignedMac\x12\x0e\n\x06serial\x18\x02 \x01(\r\x12\r\n\x05ident\x18\x03 \x01(\t\x1a \n\nDeployment\x12\x12\n\npassphrase\x18\x01 \x01(\tB4\n\x17\x63om.rajant.bcapi.protosB\x0eHardwareProtosH\x02Z\x07\x62\x63proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Hardware_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.rajant.bcapi.protosB\016HardwareProtosH\002Z\007bcproto'
  _globals['_HARDWARE']._serialized_start=33
  _globals['_HARDWARE']._serialized_end=685
  _globals['_HARDWARE_ORGANIZATION']._serialized_start=377
  _globals['_HARDWARE_ORGANIZATION']._serialized_end=441
  _globals['_HARDWARE_LINKEDDEVICE']._serialized_start=443
  _globals['_HARDWARE_LINKEDDEVICE']._serialized_end=502
  _globals['_HARDWARE_ASSIGNEDMAC']._serialized_start=504
  _globals['_HARDWARE_ASSIGNEDMAC']._serialized_end=563
  _globals['_HARDWARE_BOARDDATA']._serialized_start=565
  _globals['_HARDWARE_BOARDDATA']._serialized_end=651
  _globals['_HARDWARE_DEPLOYMENT']._serialized_start=653
  _globals['_HARDWARE_DEPLOYMENT']._serialized_end=685
# @@protoc_insertion_point(module_scope)
