# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Led.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tLed.proto\"\x1f\n\x0bLEDSequence\x12\x10\n\x08sequence\x18\x01 \x01(\tB/\n\x17\x63om.rajant.bcapi.protosB\tLedProtosH\x02Z\x07\x62\x63proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Led_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.rajant.bcapi.protosB\tLedProtosH\002Z\007bcproto'
  _globals['_LEDSEQUENCE']._serialized_start=13
  _globals['_LEDSEQUENCE']._serialized_end=44
# @@protoc_insertion_point(module_scope)
