# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Log.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Common_pb2 as Common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tLog.proto\x1a\x0c\x43ommon.proto\"\x98\x01\n\x08\x42\x43Logger\x12\x1b\n\x04logs\x18\x01 \x03(\x0b\x32\r.BCLogger.Log\x1a=\n\x06LEDLog\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x65xtraMessage\x18\x03 \x01(\t\x1a\x30\n\x03Log\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x1a\n\x06\x61\x63tion\x18\x02 \x01(\x0e\x32\n.BCRActionB/\n\x17\x63om.rajant.bcapi.protosB\tLogProtosH\x02Z\x07\x62\x63proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Log_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.rajant.bcapi.protosB\tLogProtosH\002Z\007bcproto'
  _globals['_BCLOGGER']._serialized_start=28
  _globals['_BCLOGGER']._serialized_end=180
  _globals['_BCLOGGER_LEDLOG']._serialized_start=69
  _globals['_BCLOGGER_LEDLOG']._serialized_end=130
  _globals['_BCLOGGER_LOG']._serialized_start=132
  _globals['_BCLOGGER_LOG']._serialized_end=180
# @@protoc_insertion_point(module_scope)
