# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Sam.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tSam.proto\"\xa0\x01\n\x03Sam\x12\x1c\n\x05state\x18\x02 \x01(\x0e\x32\r.Sam.SamState\"{\n\x08SamState\x12\x1c\n\x18SAM_STATE_BEACON_DISABLE\x10\x00\x12\x1b\n\x17SAM_STATE_BEACON_ENABLE\x10\x01\x12\x19\n\x15SAM_STATE_BEACON_INIT\x10\x02\x12\x19\n\x15SAM_STATE_BEACON_STOP\x10\x03\x42/\n\x17\x63om.rajant.bcapi.protosB\tSamProtosH\x02Z\x07\x62\x63proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Sam_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.rajant.bcapi.protosB\tSamProtosH\002Z\007bcproto'
  _globals['_SAM']._serialized_start=14
  _globals['_SAM']._serialized_end=174
  _globals['_SAM_SAMSTATE']._serialized_start=51
  _globals['_SAM_SAMSTATE']._serialized_end=174
# @@protoc_insertion_point(module_scope)
