# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StateMeta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fStateMeta.proto\x12\x0frajant.bc.proto\"\xc2\x01\n\tStateMeta\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x37\n\treporting\x18\x02 \x01(\x0b\x32$.rajant.bc.proto.StateMeta.Reporting\x1an\n\tReporting\x12\x16\n\x07\x65xclude\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\x1b\n\x0crateOfChange\x18\x02 \x01(\x08:\x05\x66\x61lse\x12,\n\x0etimestampField\x18\x03 \x01(\t:\x14statsTimestampMillis\"9\n\x0cStateMetaSet\x12)\n\x05\x66ield\x18\x01 \x03(\x0b\x32\x1a.rajant.bc.proto.StateMetaB5\n\x17\x63om.rajant.bcapi.protosB\x0fStateMetaProtosH\x02Z\x07\x62\x63proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'StateMeta_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.rajant.bcapi.protosB\017StateMetaProtosH\002Z\007bcproto'
  _globals['_STATEMETA']._serialized_start=37
  _globals['_STATEMETA']._serialized_end=231
  _globals['_STATEMETA_REPORTING']._serialized_start=121
  _globals['_STATEMETA_REPORTING']._serialized_end=231
  _globals['_STATEMETASET']._serialized_start=233
  _globals['_STATEMETASET']._serialized_end=290
# @@protoc_insertion_point(module_scope)
