# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Sup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tSup.proto\x12\x03sup\"\xf1\x02\n\nSupMessage\x12&\n\x06header\x18\x01 \x02(\x0e\x32\x16.sup.SupMessage.Header\x12\x30\n\x0bmessageType\x18\x02 \x02(\x0e\x32\x1b.sup.SupMessage.MessageType\x12\x0f\n\x07service\x18\x03 \x02(\t\x12\x0b\n\x03qid\x18\x04 \x01(\t\x12\x0f\n\x07maxWait\x18\x05 \x01(\x05\x12\r\n\x05quiet\x18\x06 \x01(\x08\x12.\n\nproperties\x18\x07 \x03(\x0b\x32\x1a.sup.SupMessage.Properties\x12\x14\n\x0cotherAddress\x18\x08 \x01(\t\x12\x11\n\totherPort\x18\t \x01(\r\x1a(\n\nProperties\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"\x1e\n\x06Header\x12\x14\n\x0cHEADER_VALUE\x10\x80\xe0\xd5\x9b\x07\"(\n\x0bMessageType\x12\x0b\n\x07REQUEST\x10\x00\x12\x0c\n\x08RESPONSE\x10\x01\x42&\n\x0e\x63om.rajant.supB\tSupProtosH\x02Z\x07\x62\x63proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Sup_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\016com.rajant.supB\tSupProtosH\002Z\007bcproto'
  _globals['_SUPMESSAGE']._serialized_start=19
  _globals['_SUPMESSAGE']._serialized_end=388
  _globals['_SUPMESSAGE_PROPERTIES']._serialized_start=274
  _globals['_SUPMESSAGE_PROPERTIES']._serialized_end=314
  _globals['_SUPMESSAGE_HEADER']._serialized_start=316
  _globals['_SUPMESSAGE_HEADER']._serialized_end=346
  _globals['_SUPMESSAGE_MESSAGETYPE']._serialized_start=348
  _globals['_SUPMESSAGE_MESSAGETYPE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
