# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: System.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Config_pb2 as Config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cSystem.proto\x1a\x0c\x43onfig.proto\"\xca\x01\n\x13SystemConfiguration\x12\x1e\n\rconfiguration\x18\x01 \x01(\x0b\x32\x07.Config\x12\x14\n\x0cpublicSSLKey\x18\x02 \x01(\x0c\x12\x15\n\rprivateSSLKey\x18\x03 \x01(\x0c\x12-\n\x07sshKeys\x18\x04 \x01(\x0b\x32\x1c.SystemConfiguration.SshKeys\x1a\x37\n\x07SshKeys\x12\x12\n\nauthorized\x18\x01 \x01(\x0c\x12\x0b\n\x03\x64ss\x18\x02 \x01(\x0c\x12\x0b\n\x03rsa\x18\x03 \x01(\x0c\x42\x32\n\x17\x63om.rajant.bcapi.protosB\x0cSystemProtosH\x02Z\x07\x62\x63proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'System_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.rajant.bcapi.protosB\014SystemProtosH\002Z\007bcproto'
  _globals['_SYSTEMCONFIGURATION']._serialized_start=31
  _globals['_SYSTEMCONFIGURATION']._serialized_end=233
  _globals['_SYSTEMCONFIGURATION_SSHKEYS']._serialized_start=178
  _globals['_SYSTEMCONFIGURATION_SSHKEYS']._serialized_end=233
# @@protoc_insertion_point(module_scope)
