# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Troip.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bTroip.proto\x12\x05Troip\"\xd0\x06\n\x08TroipMsg\x12/\n\x08magicNum\x18\x01 \x02(\x0e\x32\x1d.Troip.TroipMsg.TroipMagicNum\x12-\n\x07msgType\x18\x02 \x02(\x0e\x32\x1c.Troip.TroipMsg.TroipMsgType\x12\x0e\n\x06seqNum\x18\x05 \x01(\r\x12\r\n\x05index\x18\x06 \x01(\r\x12/\n\x08\x62\x63\x61piVer\x18\x07 \x01(\x0e\x32\x1d.Troip.TroipMsg.TroipMinBcapi\x12\x11\n\tserialNum\x18\x08 \x01(\t\x12\x0c\n\x04name\x18\t \x01(\t\x12\x32\n\x08\x65lection\x18\x03 \x01(\x0b\x32 .Troip.TroipMsg.TroipElectionBid\x12,\n\tsignOnOff\x18\x04 \x01(\x0b\x32\x19.Troip.TroipMsg.TroipSign\x1aQ\n\x13TroipElectionRating\x12\x0e\n\x06rating\x18\x01 \x01(\r\x12\x0e\n\x06ipaddr\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\r\x12\x0c\n\x04\x62ias\x18\x04 \x01(\x05\x1a\x85\x01\n\x10TroipElectionBid\x12\x36\n\tbidRating\x18\x01 \x01(\x0b\x32#.Troip.TroipMsg.TroipElectionRating\x12\x11\n\tbidMcaddr\x18\x02 \x01(\t\x12\x12\n\nbidMixAddr\x18\x03 \x01(\t\x12\x12\n\nbidMixPort\x18\x04 \x01(\r\x1a\x33\n\tTroipSign\x12\x12\n\nsignIpaddr\x18\x01 \x01(\t\x12\x12\n\nsignMcaddr\x18\x02 \x01(\t\".\n\rTroipMagicNum\x12\x1d\n\x15MIXMASTER_MAGIC_VALUE\x10\x80\xf0\xa5\xeb\x06\",\n\rTroipMinBcapi\x12\x1b\n\x17MIXMASTER_MINIMUM_BCAPI\x10\x02\"\xa2\x01\n\x0cTroipMsgType\x12\x1b\n\x17TROIP_MSG_TYPE_ELECTION\x10\x00\x12\x1b\n\x17TROIP_MSG_TYPE_SIGN_OFF\x10\x01\x12\x1a\n\x16TROIP_MSG_TYPE_SIGN_ON\x10\x02\x12\x1d\n\x19TROIP_MSG_TYPE_CRASH_CTRL\x10\x03\x12\x1d\n\x19TROIP_MSG_TYPE_CRASH_VOIP\x10\x04\x42\x31\n\x17\x63om.rajant.bcapi.protosB\x0bTroipProtosH\x02Z\x07\x62\x63proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Troip_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.rajant.bcapi.protosB\013TroipProtosH\002Z\007bcproto'
  _globals['_TROIPMSG']._serialized_start=23
  _globals['_TROIPMSG']._serialized_end=871
  _globals['_TROIPMSG_TROIPELECTIONRATING']._serialized_start=342
  _globals['_TROIPMSG_TROIPELECTIONRATING']._serialized_end=423
  _globals['_TROIPMSG_TROIPELECTIONBID']._serialized_start=426
  _globals['_TROIPMSG_TROIPELECTIONBID']._serialized_end=559
  _globals['_TROIPMSG_TROIPSIGN']._serialized_start=561
  _globals['_TROIPMSG_TROIPSIGN']._serialized_end=612
  _globals['_TROIPMSG_TROIPMAGICNUM']._serialized_start=614
  _globals['_TROIPMSG_TROIPMAGICNUM']._serialized_end=660
  _globals['_TROIPMSG_TROIPMINBCAPI']._serialized_start=662
  _globals['_TROIPMSG_TROIPMINBCAPI']._serialized_end=706
  _globals['_TROIPMSG_TROIPMSGTYPE']._serialized_start=709
  _globals['_TROIPMSG_TROIPMSGTYPE']._serialized_end=871
# @@protoc_insertion_point(module_scope)
